# Generated by Django 5.0.7 on 2026-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(default='LearnSphere', max_length=120)),
                ('courses_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
